title: "Voglio Solo Risparmiare"
description: "Offerte selezionate per chi vuole pagare meno. Senza giri di parole."

url: "https://claudiostoduto.github.io"
baseurl: "/amazonsite"

markdown: kramdown
timezone: Europe/Rome
future: false
