title: "Voglio Solo Risparmiare"
description: "Offerte selezionate per chi vuole pagare meno. Senza giri di parole."

url: "https://vogliosolorisparmiare.it"
baseurl: ""

markdown: kramdown
timezone: Europe/Rome
future: false
permalink: /:year/:month/:day/:title/

telegram_url: "https://t.me/vogliosolorisparmiare"   # <-- cambia
